version: "3.8"

services:
  node-app:
    container_name: node-app-dev
    command: pnpm dev
    env_file:
      - .env
    volumes:
      - .:/usr/src/node-app
      - /usr/src/node-app/node_modules

  postgresdb:
    ports:
      - "5432:5432"
