ALTER TABLE "MealLog" DROP COLUMN IF EXISTS "eatenAt";

ALTER TABLE "MealLog" ADD COLUMN IF NOT EXISTS "customName" TEXT;
ALTER TABLE "MealLog" ADD COLUMN IF NOT EXISTS "isCustom" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "MealLog" ADD COLUMN IF NOT EXISTS "tag" TEXT;

DROP INDEX IF EXISTS "MealLog_eatenAt_idx";

CREATE INDEX IF NOT EXISTS "MealLog_createdAt_idx" ON "MealLog"("createdAt");